// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzPHPxnLgFKD2ykF_OkLeAjKB-Ryef5VU',
    appId: '1:335480039067:web:a447ed407b42596b13883e',
    messagingSenderId: '335480039067',
    projectId: 'flutter-voice-call-app',
    authDomain: 'flutter-voice-call-app.firebaseapp.com',
    storageBucket: 'flutter-voice-call-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxO0_cd5g5eVfb_F37fLxw9Gqr_BPmtsY',
    appId: '1:335480039067:android:667171b0462d6be713883e',
    messagingSenderId: '335480039067',
    projectId: 'flutter-voice-call-app',
    storageBucket: 'flutter-voice-call-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBeSvTqW89X7xAOcn_L5wklELNcg_BCdk',
    appId: '1:335480039067:ios:3f4a72b676f1c84513883e',
    messagingSenderId: '335480039067',
    projectId: 'flutter-voice-call-app',
    storageBucket: 'flutter-voice-call-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterVoicecallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBeSvTqW89X7xAOcn_L5wklELNcg_BCdk',
    appId: '1:335480039067:ios:3f4a72b676f1c84513883e',
    messagingSenderId: '335480039067',
    projectId: 'flutter-voice-call-app',
    storageBucket: 'flutter-voice-call-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterVoicecallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzPHPxnLgFKD2ykF_OkLeAjKB-Ryef5VU',
    appId: '1:335480039067:web:170537e6252619aa13883e',
    messagingSenderId: '335480039067',
    projectId: 'flutter-voice-call-app',
    authDomain: 'flutter-voice-call-app.firebaseapp.com',
    storageBucket: 'flutter-voice-call-app.firebasestorage.app',
  );
}
